### PR TITLE
Fix the issue with python-lint job - pylint command

### PR DESCRIPTION
**Pull request by rakshithakamath94**

### CODE REVIEW

**Comment by mscherer** [comment]
This seems good, but why -false -o ? From my understanding, that's "false or", which mean that it always evalute to the condition after the -o.

**Comment by rakshithakamath94** [comment]
Surprisingly if when I didn't include -false option in the pylint-check.txt file I could see ./env listed. But again when I ran it from jenkins environment without -false option that path is not showing in the pylint-check.txt file. Let me try one more time and will update you on the same.

**Comment by rakshithakamath94** [comment]
@mscherer I have another doubt!

if [[ "$FLAKE_COUNT" -gt 0  && "$PYLINT_COUNT" -gt 0 ]]; then

should this be a "AND" condition or an "OR" condition.

For example:

Right now the value of  FLAKE_COUNT and PYLINT_COUNT evaluates to 1723 and 0 respectively.
In this case the "AND" condition will evaluates to 0 && 1 which will make it false but in reality should it evaluate to true or false?

I was thinking may be we have to change it to logical "OR" condition so that when one of them is greater than 0 it will fail the job and print the number of FLAKE8 and PYLINT issues.

Again if there's a issue I feel like we need to print it on the console and mark build as success because the point of this job is to intimate people about the number of issues so the job shouldn't be marked as failure.

**Comment by mscherer** [comment]
Could be a difference between EL 7 and Fedora/EL8, so if that's what is working, i guess that's good. I would then update the line above for consistency.

**Comment by mscherer** [comment]
And you are right, this should be a OR, not a AND.

**Comment by rakshithakamath94** [comment]
Regarding -false option.

I had tested it without -print option. If I put -print there's no need to put option -false

Here's the example,
[root@builder]# find . -path './env' -prune -o -name 'main.sh'
./env
./main.sh
[root@builder]# find . -path './env' -prune -o -name 'main.sh' -print
./main.sh

so I will go ahead and remove -false option from the command

**Comment by deepshikhaaa** [comment]
With `exit 1` commented out, it will most likely not notify about the actual failure. FOr now we can just keep it as it is and see if there are any new failures for both, or we can keep just one linter?

**Comment by deepshikhaaa** [comment]
@mscherer what do you think?

**Comment by mscherer** [comment]
I think that's a linter, we can't fail when it successfully report errors/warnings since we have them since forever (if we had a policy of 0 warnings, that would be different). I posted in the chat a plugin that would help (https://plugins.jenkins.io/warnings-ng/), but for now, the current patch seems good.

Transitioning to a better systems for linter warnings seems like a bigger task. I also wonder if we should split pylint and flake8 in 2 differents jobs, so we can handle failure separately later (especially since warnings-ng work with 1 linter per job).

**Comment by rakshithakamath94** [comment]
Should I make it 2 jobs one for pylint and flake8 each and send a PR?

**Comment by mscherer** [comment]
I think 2 jobs would be a good idea, but let's not wait, since this was blocking people (which I didn't realize), I should have merged it sooner.

**Pull request merged**
