### PR TITLE
Adding admin list to jobs/glusto-tests-lint.yml

### PR DESCRIPTION
**Pull request by kshithijiyer**
Based on discussion on https://github.com/gluster/build-jobs/pull/72 adding admin list to jobs/glusto-tests-lint.yml

### CODE REVIEW

**Comment by kshithijiyer** [comment]
@deepshikhaaa @mscherer @aloganat can you please review?

**Comment by mscherer** [comment]
Syntax look good. I would prefer to use a Github team, but jjb do not support that.

**Comment by kshithijiyer** [comment]
> Syntax look good. I would prefer to use a Github team, but jjb do not support that.

One other thing which we can do is if you could add the QE team to the gluster github org it'll also solve the problem and we'll get the needed rights. 

Would suggest to add me or @aloganat so that we can invite the reset of the team to the org.

**Comment by deepshikhaaa** [comment]
We follow this contributing guide https://github.com/gluster/glusterfs/blob/devel/CONTRIBUTING.md to be a member of gluster org. I think it is fine to have a list for now.

**Pull request merged**
