### PR TITLE
Add regression output in case of success too

### PR DESCRIPTION
**Pull request by amarts**
This will allow reviewers to look at tests which needed retry,
and also the tests which are flaky.

Updates: gluster/project-infrastructure#72
Change-Id: I9d5db026bc47d612b05fc74622f1e0c000ba4f35
Signed-off-by: Amar Tumballi <amar@kadalu.io>

### CODE REVIEW

**Comment by amarts** [comment]
This along with https://review.gluster.org/24883/ will allow now flaky tests to continue running, but if they fail, it gets marked as 'flaky', and will be shown along with SUCCESS message too in Gerrit.

**Comment by deepshikhaaa** [comment]
Thanks for taking care of the flaky tests. Looks good to me.

**Review by deepshikhaaa — APPROVED** [review]

**Comment by amarts** [comment]
This alone doesn't add much value. This along with the changes @ https://review.gluster.org/#/c/glusterfs/+/24883/11/run-tests.sh, which actually adds failures of FLAKY tests to output in Success case also would make this solution complete.

Next time anyone says there is a flaky test, ask them to add it to `tests/000-flaky/` directory in glusterfs project itself. Infra team doesn't need to look at it :+1:

**Comment by amarts** [comment]
@mscherer merging without your vote. As the glusterfs patch is merged, it would be great to have this. Happy to work on any comments as soon as they are given.

**Pull request merged**
