### PR TITLE
Add smoke test on C8, and use AWS hosts for the tests

### PR DESCRIPTION
**Pull request by mscherer**

### CODE REVIEW

**Comment by deepshikhaaa** [comment]
I remember smoke was failing on centos8.

**Comment by mscherer** [comment]
Let's see how it goes now

**Comment by mscherer** [comment]
I mean, let me test smoke8 first :p

**Comment by mscherer** [comment]
Ok so this will wait after the jenkins restart

**Comment by mscherer** [comment]
Ok so smoke need to stay in the cage for now, because that's where we upload the CI-logs

**Pull request closed without merging**
